from pathlib import Path

OUT = Path(__file__).parent / 'dist'

NAV = [('Início','/'),('Serviços','/servicos.html'),('Planos','/planos.html'),('Sobre','/sobre.html'),('Contato','/contato.html')]
ICON = "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Crect width='64' height='64' fill='%230b0b0b'/%3E%3Cpath fill='white' d='M15 12h20c12 0 19 7 19 18s-7 18-19 18H27v9H15V12zm12 11v14h8c5 0 7-3 7-7s-2-7-7-7h-8z'/%3E%3Cpath d='m31 44 7-5 6 2 9-11' fill='none' stroke='white' stroke-width='3'/%3E%3C/svg%3E"

def page(title, desc, body, active=''):
    links = ''.join(f'<a href="{url}" class="{"active" if label == active else ""}">{label}</a>' for label,url in NAV)
    return f'''<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#0a0a0a"><meta name="description" content="{desc}"><title>{title} | Prates Digital</title><link rel="icon" type="image/svg+xml" href="{ICON}"><link rel="preconnect" href="https://images.unsplash.com"><link rel="stylesheet" href="/style.css"></head><body>
    <a class="skip" href="#conteudo">Pular para o conteúdo</a><div class="progress" aria-hidden="true"></div>
    <header class="header"><div class="wrap nav"><a href="/" class="brand" aria-label="Prates Digital, início"><span class="brand-mark">P<span class="rise">↗</span></span><span>PRATES<span class="brand-light">DIGITAL</span></span></a><button class="menu-toggle" type="button" aria-label="Abrir menu" aria-expanded="false" aria-controls="menu"><span></span><span></span></button><nav id="menu" class="menu" aria-label="Navegação principal">{links}<a class="nav-cta" href="/contato.html">Pedir orçamento <span aria-hidden="true">↗</span></a></nav></div></header>
    <main id="conteudo">{body}</main>
    <footer class="footer"><div class="wrap"><div class="footer-top"><div><a href="/" class="brand footer-brand"><span class="brand-mark">P<span class="rise">↗</span></span><span>PRATES<span class="brand-light">DIGITAL</span></span></a><p>Boas ideias precisam de presença, processo e continuidade.</p></div><div><span class="eyebrow">Explore</span><a href="/servicos.html">Serviços</a><a href="/planos.html">Planos</a><a href="/sobre.html">Quem somos</a></div><div><span class="eyebrow">Converse</span><a href="/contato.html">Solicitar orçamento</a><a href="#" data-contact="whatsapp">WhatsApp</a><a href="#" data-contact="email">E-mail</a></div></div><div class="footer-bottom"><span>© 2026 Prates Digital. Guarulhos, SP.</span><a href="/privacidade.html">Privacidade</a><span>Feito para funcionar em qualquer tela.</span></div></div></footer>
    <script src="/config.js"></script><script src="/script.js" defer></script></body></html>'''

home = '''
<section class="hero wrap"><div class="hero-copy reveal"><div class="section-tag"><i></i> ESTÚDIO DIGITAL · GUARULHOS, SP</div><h1>Sua marca merece <em>ser vista.</em><br>Sua operação precisa <em>funcionar.</em></h1><p>Criamos sites, conteúdo e automações que ajudam negócios a se apresentar melhor, atender com mais agilidade e crescer com direção.</p><div class="hero-actions"><a class="button light" href="/contato.html">Conte o seu projeto <span>↗</span></a><a class="text-link" href="/servicos.html">Conhecer serviços <span>↗</span></a></div><div class="hero-meta"><span>Estratégia</span><b></b><span>Design</span><b></b><span>Tecnologia</span></div></div><div class="hero-visual"><img src="https://images.unsplash.com/photo-1766575288603-2cbd899428a4?auto=format&amp;fit=crop&amp;w=1300&amp;q=78" alt="Fachada de edifício moderno com linhas geométricas" fetchpriority="high"><div class="visual-caption"><span>01 / VISÃO</span><strong>Uma presença que trabalha<br>com você.</strong></div></div></section>
<section class="statement wrap reveal"><span class="eyebrow">O QUE FAZEMOS</span><p>Do primeiro contato à próxima venda, cuidamos dos pontos onde sua marca encontra pessoas.</p><a href="/servicos.html" class="round-link" aria-label="Explorar todos os serviços">↗</a></section>
<section class="services-section"><div class="wrap"><div class="section-heading reveal"><div><span class="eyebrow">SERVIÇOS</span><h2>Uma marca inteira.<br><span class="muted">Não só uma página.</span></h2></div><p>Você pode começar por uma necessidade e ampliar depois. O plano acompanha o momento do negócio.</p></div><div class="service-grid"><a class="service-card reveal" href="/servicos.html#presenca"><span class="num">01</span><div class="glyph">⌁</div><h3>Sites & presença digital</h3><p>Sites institucionais, landing pages, páginas de venda e presença local que explicam bem o que você faz.</p><span class="card-link">Ver detalhes ↗</span></a><a class="service-card reveal" href="/servicos.html#automacao"><span class="num">02</span><div class="glyph">✳</div><h3>Bots & automação</h3><p>Fluxos de atendimento, triagem e respostas assistidas para WhatsApp e Instagram, com passagem para uma pessoa.</p><span class="card-link">Ver detalhes ↗</span></a><a class="service-card reveal" href="/servicos.html#conteudo"><span class="num">03</span><div class="glyph">◈</div><h3>Marca & conteúdo</h3><p>Identidade visual, peças, vídeos e gestão de canais com linguagem que combina com o seu público.</p><span class="card-link">Ver detalhes ↗</span></a><a class="service-card reveal" href="/servicos.html#crescimento"><span class="num">04</span><div class="glyph">↗</div><h3>Crescimento & mídia</h3><p>Perfil da Empresa no Google, SEO local, campanhas e acompanhamento para ajustar o que dá resultado.</p><span class="card-link">Ver detalhes ↗</span></a></div></div></section>
<section class="feature wrap"><div class="feature-image reveal"><img loading="lazy" src="https://images.unsplash.com/photo-1770816306485-862b40ecc402?auto=format&amp;fit=crop&amp;w=1100&amp;q=76" alt="Arquitetura contemporânea com linhas e iluminação suaves"></div><div class="feature-copy reveal"><span class="eyebrow">UM JEITO MAIS CLARO DE CRESCER</span><h2>Primeiro, entendemos.<br>Depois, construímos.</h2><p>Não existe botão mágico para vender. Existe uma boa leitura do negócio, uma proposta objetiva, execução cuidadosa e melhoria contínua.</p><div class="steps-mini"><div><span>01</span><strong>Diagnóstico</strong><small>Objetivo, público e momento da empresa.</small></div><div><span>02</span><strong>Plano em PDF</strong><small>Escopo, entregas, prazos e prioridades.</small></div><div><span>03</span><strong>Execução & suporte</strong><small>Acompanhamento e ajustes acordados.</small></div></div><a href="/sobre.html" class="text-link">Como trabalhamos ↗</a></div></section>
<section class="plans-preview"><div class="wrap"><div class="section-heading reveal"><div><span class="eyebrow">PLANOS MENSAIS</span><h2>Comece pelo que<br>faz sentido agora.</h2></div><p>Combinações iniciais para dar previsibilidade. O escopo final é fechado depois do diagnóstico.</p></div><div class="plan-strip"><div class="plan-tile reveal"><span>01 / ESSENCIAL</span><h3>Presença</h3><p>Para organizar a marca e manter uma comunicação ativa.</p><strong>R$ 790 <small>/ mês</small></strong><a href="/planos.html">Ver o plano ↗</a></div><div class="plan-tile featured reveal"><span>02 / MAIS ESCOLHIDO</span><h3>Crescimento</h3><p>Conteúdo, presença local e acompanhamento em uma rotina só.</p><strong>R$ 1.690 <small>/ mês</small></strong><a href="/planos.html">Ver o plano ↗</a></div><div class="plan-tile reveal"><span>03 / SOB MEDIDA</span><h3>Operação</h3><p>Mais canais, automações e uma cadência de evolução.</p><strong>R$ 3.290 <small>/ mês</small></strong><a href="/planos.html">Ver o plano ↗</a></div></div><p class="pricing-note">Valores iniciais de referência. Implantação, mídia paga e ferramentas externas são orçadas à parte.</p></div></section>
<section class="manifesto wrap reveal"><span class="eyebrow">A PRATES DIGITAL</span><h2>O digital precisa<br><span>parecer com a sua empresa.</span></h2><div><p>Trabalhamos com negócios de diferentes tamanhos. Cada projeto parte da identidade e das prioridades de quem está do outro lado da mesa.</p><a class="button outline" href="/sobre.html">Conheça a equipe ↗</a></div></section>
<section class="faq wrap"><div class="section-heading reveal"><div><span class="eyebrow">DÚVIDAS FREQUENTES</span><h2>Antes de começar.</h2></div></div><div class="faq-list"><details><summary>Vocês atendem empresas fora de Guarulhos?</summary><p>Sim. O atendimento e as entregas podem acontecer remotamente em todo o Brasil. Projetos fora do país são avaliados caso a caso, conforme idioma, fuso e necessidades de suporte.</p></details><details><summary>O bot de IA substitui uma pessoa?</summary><p>Não recomendamos isso para todos os casos. Desenhamos respostas, triagem e encaminhamento, incluindo uma saída clara para atendimento humano. Integrações dependem das plataformas e das contas do cliente.</p></details><details><summary>O que está incluído no valor mensal?</summary><p>Cada plano indica uma base de entregas e suporte. Após o diagnóstico, enviamos uma proposta em PDF com escopo, responsabilidades, prazos e condições. Verba de anúncios e cobranças de terceiros não entram na mensalidade.</p></details><details><summary>Posso contratar apenas um site?</summary><p>Sim. Projetos avulsos, como sites, identidade, vídeos e configuração de automações, podem ser contratados separadamente, com suporte opcional.</p></details></div></section>
<section class="cta-band"><div class="wrap reveal"><span class="eyebrow">VAMOS CONVERSAR?</span><h2>Conte onde você está.<br>A gente pensa no próximo passo.</h2><a class="button dark" href="/contato.html">Solicitar um orçamento ↗</a></div></section>'''

services = '''<section class="page-hero wrap reveal"><span class="eyebrow">SERVIÇOS</span><h1>O que a sua empresa precisa <em>agora?</em></h1><p>Projetos pontuais e acompanhamento mensal, da primeira ideia à operação do dia a dia.</p></section>
<section class="detail-list wrap"><article id="presenca" class="detail-row reveal"><div class="detail-index">01 / PRESENÇA</div><div><h2>Seu melhor endereço no digital.</h2><p>Um site claro ajuda o cliente a entender sua oferta, confiar no seu trabalho e saber como entrar em contato.</p><ul><li>Site institucional e landing page responsivos</li><li>Páginas de serviços, portfólio e contato</li><li>Estrutura básica para busca, velocidade e acessibilidade</li><li>Perfil da Empresa no Google e SEO local</li></ul><a href="/contato.html?servico=Site%20e%20presen%C3%A7a%20digital" class="text-link">Conversar sobre presença ↗</a></div></article>
<article id="automacao" class="detail-row reveal"><div class="detail-index">02 / AUTOMAÇÃO</div><div><h2>Atendimento que não perde o contexto.</h2><p>Organizamos perguntas frequentes, qualificamos pedidos e encaminhamos o que precisa de uma pessoa. A IA entra onde ela realmente ajuda.</p><ul><li>Bot de WhatsApp e Instagram, conforme integração disponível</li><li>Fluxos de triagem, agendamento e pré-atendimento</li><li>Base de respostas, revisão e passagem para humano</li><li>Integrações com formulários e ferramentas do negócio</li></ul><div class="callout">Custos de API, provedores e requisitos das plataformas são definidos na proposta. Automação não garante resposta perfeita nem substitui revisão humana.</div><a href="/contato.html?servico=Bot%20e%20automa%C3%A7%C3%A3o" class="text-link">Desenhar uma automação ↗</a></div></article>
<article id="conteudo" class="detail-row reveal"><div class="detail-index">03 / MARCA</div><div><h2>Uma voz reconhecível em cada canal.</h2><p>Construímos uma comunicação coerente para que sua empresa seja lembrada pelo que entrega, não por seguir uma fórmula genérica.</p><ul><li>Identidade visual e peças para campanhas</li><li>Planejamento e gestão de Instagram</li><li>Edição de vídeos curtos e materiais digitais</li><li>Calendário editorial e revisão de linguagem</li></ul><a href="/contato.html?servico=Marca%20e%20conte%C3%BAdo" class="text-link">Conversar sobre conteúdo ↗</a></div></article>
<article id="crescimento" class="detail-row reveal"><div class="detail-index">04 / CRESCIMENTO</div><div><h2>Menos achismo. Mais leitura do caminho.</h2><p>Unimos presença local, campanhas e acompanhamento para aprender com os dados e priorizar ações úteis.</p><ul><li>Otimização do Perfil da Empresa no Google</li><li>Estratégia de vendas e jornada de contato</li><li>Campanhas de mídia paga e testes criativos</li><li>Relatórios objetivos e recomendações mensais</li></ul><div class="callout">Investimento em anúncios é pago diretamente pelo cliente às plataformas e não está incluído nos honorários.</div><a href="/contato.html?servico=Crescimento%20e%20m%C3%ADdia" class="text-link">Planejar crescimento ↗</a></div></article></section>
<section class="cta-band"><div class="wrap reveal"><span class="eyebrow">NÃO SABE POR ONDE COMEÇAR?</span><h2>Descreva o seu desafio.<br>O caminho vem depois.</h2><a href="/contato.html" class="button dark">Pedir diagnóstico ↗</a></div></section>'''

plans = '''<section class="page-hero wrap reveal"><span class="eyebrow">PLANOS E INVESTIMENTO</span><h1>Previsibilidade para <em>continuar crescendo.</em></h1><p>Preços de referência para uma primeira conversa. A proposta em PDF define entregas, cronograma, suporte e valores finais.</p></section>
<section class="wrap pricing-grid"><article class="pricing-card reveal"><span class="eyebrow">01 / PRESENÇA</span><h2>Essencial</h2><p>Para começar com uma comunicação consistente.</p><div class="price">R$ 790 <small>/ mês</small></div><div class="setup">Implantação sugerida: R$ 1.290</div><ul><li>Diagnóstico e plano de ação inicial</li><li>Até 8 peças digitais por mês</li><li>Calendário e revisão de conteúdo</li><li>Otimização inicial do perfil no Google</li><li>Reunião e relatório mensal</li><li>Suporte por mensagem em horário comercial</li></ul><a href="/contato.html?plano=Essencial" class="button outline">Pedir proposta ↗</a></article>
<article class="pricing-card prime reveal"><span class="eyebrow">02 / CRESCIMENTO</span><h2>Crescimento</h2><p>Para conectar conteúdo, presença e aquisição.</p><div class="price">R$ 1.690 <small>/ mês</small></div><div class="setup">Implantação sugerida: R$ 2.490</div><ul><li>Tudo do Essencial</li><li>Até 12 peças e 4 vídeos curtos por mês</li><li>Gestão de um canal social</li><li>Otimização contínua de presença local</li><li>Gestão de uma frente de anúncios*</li><li>Reunião quinzenal e relatório</li></ul><a href="/contato.html?plano=Crescimento" class="button light">Pedir proposta ↗</a></article>
<article class="pricing-card reveal"><span class="eyebrow">03 / OPERAÇÃO</span><h2>Operação</h2><p>Para integrar canais e atendimento em uma rotina maior.</p><div class="price">R$ 3.290 <small>/ mês</small></div><div class="setup">Implantação sugerida: R$ 3.990</div><ul><li>Tudo do Crescimento</li><li>Até 20 peças e 8 vídeos curtos por mês</li><li>Gestão de até dois canais sociais</li><li>Planejamento de automação e um fluxo inicial</li><li>Acompanhamento semanal</li><li>Prioridade de suporte em horário comercial</li></ul><a href="/contato.html?plano=Operação" class="button outline">Pedir proposta ↗</a></article></section>
<section class="wrap pricing-explainer"><p>* Verba de mídia paga, hospedagem, domínio, licenças, APIs e produção presencial são cobrados à parte. O escopo e o prazo de suporte são formalizados antes da contratação. Valores em reais, sujeitos a ajuste conforme complexidade.</p></section>
<section class="wrap addon-section reveal"><div><span class="eyebrow">PROJETOS AVULSOS</span><h2>Precisa de uma peça específica?</h2><p>Também desenvolvemos soluções pontuais. São pontos de partida para orçamento, não uma promessa de preço fechado.</p></div><div class="addon-list"><div><span>Site institucional</span><strong>a partir de R$ 2.900</strong></div><div><span>Landing page</span><strong>a partir de R$ 1.490</strong></div><div><span>Identidade visual</span><strong>a partir de R$ 1.200</strong></div><div><span>Bot e fluxo inicial</span><strong>a partir de R$ 2.490</strong></div><div><span>Suporte mensal de site</span><strong>a partir de R$ 290/mês</strong></div><div><span>Suporte mensal de bot</span><strong>a partir de R$ 590/mês</strong></div></div></section>
<section class="process-section"><div class="wrap"><div class="section-heading reveal"><div><span class="eyebrow">DO CONTATO À ENTREGA</span><h2>Você sabe o que acontece depois.</h2></div></div><div class="process-grid"><div><span>01</span><h3>Conversa</h3><p>Entendemos objetivo, público, prazo e orçamento.</p></div><div><span>02</span><h3>Proposta em PDF</h3><p>Escopo, entregas, cronograma, investimento e responsabilidades.</p></div><div><span>03</span><h3>Produção</h3><p>Alinhamentos, execução e aprovação em etapas.</p></div><div><span>04</span><h3>Continuidade</h3><p>Suporte, análise e ajustes dentro do plano contratado.</p></div></div></div></section>
<section class="cta-band"><div class="wrap reveal"><span class="eyebrow">UMA PROPOSTA PARA O SEU CONTEXTO</span><h2>Vamos encontrar o formato certo?</h2><a href="/contato.html" class="button dark">Solicitar orçamento ↗</a></div></section>'''

about = '''<section class="page-hero wrap reveal"><span class="eyebrow">SOBRE NÓS</span><h1>Uma agência pequena o bastante para ouvir. <em>Ambiciosa o bastante para construir.</em></h1><p>A Prates Digital reúne estratégia, criação e tecnologia para aproximar negócios das pessoas certas.</p></section>
<section class="wrap about-lead"><div class="about-image"><img loading="lazy" src="https://images.unsplash.com/photo-1766575288603-2cbd899428a4?auto=format&amp;fit=crop&amp;w=1100&amp;q=76" alt="Detalhe geométrico de arquitetura moderna"></div><div class="reveal"><span class="eyebrow">NOSSO PONTO DE PARTIDA</span><h2>Seu negócio tem uma história. O digital deve ajudar a contá-la.</h2><p>Trabalhamos para transformar objetivos em experiências claras: uma página que explica, um conteúdo que conversa e um atendimento que organiza o próximo passo.</p><p>Não vendemos crescimento automático. Propomos trabalho bem definido, acompanhamento e espaço para melhorar.</p></div></section>
<section class="team-section"><div class="wrap"><div class="section-heading reveal"><div><span class="eyebrow">EQUIPE</span><h2>Pessoas por trás<br>dos projetos.</h2></div><p>Você fala diretamente com quem pensa e executa a solução.</p></div><div class="team-grid"><article class="team-card"><span class="team-initial">J</span><h3>Joaquim</h3><p>Estratégia digital e desenvolvimento.</p></article><article class="team-card"><span class="team-initial">K</span><h3>Kauã</h3><p>Criação e operação digital.</p></article></div><p class="team-note">Papéis e participação são ajustados conforme o projeto.</p></div></section>
<section class="wrap reach-section reveal"><div><span class="eyebrow">ONDE ATENDEMOS</span><h2>De Guarulhos para onde houver um bom projeto.</h2></div><div><p>Estamos em Guarulhos, São Paulo. O atendimento remoto alcança negócios em todo o Brasil. Para projetos internacionais, avaliamos disponibilidade, idioma e fuso antes de assumir o suporte.</p><div class="region-tags"><span>Guarulhos e Grande São Paulo</span><span>Brasil, remotamente</span><span>Exterior, sob consulta</span></div></div></section>
<section class="wrap testimonial-section"><span class="eyebrow">RELAÇÕES REAIS</span><h2>A confiança vem do trabalho.</h2><p>Publicaremos depoimentos e projetos somente com autorização de cada cliente. Enquanto isso, nossa proposta detalha o que vamos entregar e como acompanhar cada etapa.</p></section>
<section class="cta-band"><div class="wrap reveal"><span class="eyebrow">VAMOS NOS APRESENTAR?</span><h2>Conte um pouco sobre o seu negócio.</h2><a href="/contato.html" class="button dark">Falar com a equipe ↗</a></div></section>'''

contact = '''<section class="page-hero wrap reveal"><span class="eyebrow">CONTATO</span><h1>Vamos conversar sobre <em>o seu próximo passo.</em></h1><p>Preencha o essencial. Ao enviar, abrimos uma mensagem pronta no WhatsApp da Prates Digital para você revisar e confirmar.</p></section>
<section class="wrap contact-layout"><div class="contact-side reveal"><h2>Uma boa conversa começa com contexto.</h2><p>Pode falar do desafio, do prazo ou só contar a ideia. A gente organiza as perguntas depois.</p><div class="contact-facts"><div><span>BASE</span><strong>Guarulhos, São Paulo</strong></div><div><span>ATENDIMENTO</span><strong>Remoto em todo o Brasil<br>Exterior sob consulta</strong></div><div><span>E-MAIL</span><a href="#" data-contact="email">Abrir e-mail ↗</a></div><div><span>WHATSAPP</span><a href="#" data-contact="whatsapp">Iniciar conversa ↗</a></div></div></div><form class="quote-form reveal" id="quote-form"><div class="form-heading"><span class="eyebrow">PEDIR ORÇAMENTO</span><h2>Conte sobre o projeto</h2><p>Os campos com * são obrigatórios.</p></div><div class="field-row"><label>Seu nome *<input name="nome" autocomplete="name" required maxlength="100" placeholder="Como podemos chamar você?"></label><label>Seu e-mail *<input name="email" type="email" autocomplete="email" required maxlength="160" placeholder="voce@empresa.com"></label></div><label>Empresa ou projeto<input name="empresa" autocomplete="organization" maxlength="120" placeholder="Opcional"></label><fieldset><legend>O que você procura? *</legend><div class="checks"><label><input type="checkbox" name="servico" value="Site e presença digital"> Site e presença digital</label><label><input type="checkbox" name="servico" value="Bot e automação"> Bot e automação</label><label><input type="checkbox" name="servico" value="Marca e conteúdo"> Marca e conteúdo</label><label><input type="checkbox" name="servico" value="Crescimento e mídia"> Crescimento e mídia</label><label><input type="checkbox" name="servico" value="Ainda não sei"> Ainda não sei</label></div></fieldset><label>Plano de interesse<select name="plano"><option value="">Escolha se já souber</option><option>Essencial</option><option>Crescimento</option><option>Operação</option><option>Projeto avulso</option></select></label><label>Descreva o que você precisa *<textarea name="descricao" required maxlength="2000" rows="6" placeholder="O que sua empresa faz? O que você quer melhorar? Há algum prazo?"></textarea></label><div class="form-error" role="alert" hidden></div><button type="submit" class="button light">Enviar pelo WhatsApp ↗</button><p class="form-note">Ao clicar, o WhatsApp abre com os dados preenchidos. A mensagem só é enviada quando você confirma no aplicativo. <a href="/privacidade.html">Como tratamos esses dados</a>.</p><a class="alt-mail" href="#" id="email-form">Prefere enviar por e-mail? ↗</a></form></section>'''

privacy = '''<section class="page-hero wrap"><span class="eyebrow">PRIVACIDADE</span><h1>Clareza também vale para os seus dados.</h1><p>Esta página explica o que acontece quando você entra em contato pelo site.</p></section><section class="wrap legal-copy"><h2>Formulário de orçamento</h2><p>Nome, e-mail, empresa, serviço, plano e descrição são usados para montar uma mensagem no seu próprio dispositivo. Este site não mantém um cadastro desses dados. Ao optar por WhatsApp ou e-mail, você revisa e envia a mensagem pelo serviço escolhido, sujeito às regras da plataforma.</p><h2>Contato e finalidade</h2><p>Os dados que você enviar poderão ser usados pela Prates Digital para responder à solicitação, preparar uma proposta e acompanhar a conversa comercial. Para corrigir ou pedir a exclusão de informações compartilhadas diretamente conosco, use o canal de contato indicado neste site.</p><h2>Recursos externos</h2><p>Fotografias são carregadas do Unsplash. O site não usa ferramentas próprias de análise comportamental nem cookies de publicidade nesta versão. Links para WhatsApp e o seu aplicativo de e-mail abrem serviços externos.</p><p>Texto informativo da versão inicial. Revise os dados de contato e a política conforme a operação real antes da divulgação pública.</p></section>'''

pages = [
    ('index.html', 'Agência digital para marcas em movimento', 'Sites, bots, conteúdo e estratégia digital. Conheça a Prates Digital.', home, 'Início'),
    ('servicos.html', 'Serviços', 'Sites, automação, bots de IA, conteúdo, identidade visual e crescimento digital.', services, 'Serviços'),
    ('planos.html', 'Planos e preços', 'Planos mensais e projetos avulsos da Prates Digital, com valores iniciais de referência.', plans, 'Planos'),
    ('sobre.html', 'Sobre nós', 'Conheça a equipe, a forma de trabalhar e a área de atendimento da Prates Digital.', about, 'Sobre'),
    ('contato.html', 'Pedir orçamento', 'Conte sobre seu projeto e envie uma solicitação de orçamento pelo WhatsApp ou e-mail.', contact, 'Contato'),
    ('privacidade.html', 'Privacidade', 'Saiba como os dados do formulário de contato são tratados.', privacy, '')
]
for filename,title,desc,body,active in pages:
    (OUT / filename).write_text(page(title, desc, body, active), encoding='utf-8')
